### ISSUE TITLE
运行test后有报错_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by dadazhetang** [USTC-xlab/MOSR#1]
我在远程服务器中使用命令行python basicsr/test.py -opt options/test/test_ESRGAN_x4_MOSR.yml运行代码，结果报错_pickle.UnpicklingError: pickle data was truncated，尝试过重新传输数据和换取内存更大的GPU运行不过仍然报错_pickle.UnpicklingError: pickle data was truncated。
完整报错信息
Traceback (most recent call last):
  File "/root/autodl-tmp/.autodl/basicsr/test.py", line 45, in <module>
    test_pipeline(root_path)
  File "/root/autodl-tmp/.autodl/basicsr/test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/sr_model.py", line 30, in __init__
    self.load_network(self.net_g, load_path, self.opt['path'].get('strict_load_g', True), param_key)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/base_model.py", line 290, in load_network
    load_net = torch.load(load_path, map_location=lambda storage, loc: storage)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

请问我应该怎么解决？

**Comment by USTC-xlab** [comment]
This appears to be due to file corruption and you can re-generate a low resolution MSI image. Also note that our input folder is specified in the `yml` file and does not require the pickle library to import.

**Comment by dadazhetang** [comment]
I tried to find out where the corruptive files are and found that the "pretrained_models" provided in the github contains just a ".md" file,which says "The pretrained model is released as v2.0.0.".Maybe that's the problem?

**Comment by dadazhetang** [comment]
I tried to find out where the corruptive files are and found that the "pretrained_models" provided in the github contains just a ".md" file,which says "The pretrained model is released as v2.0.0.".Maybe that's the problem?


                       
原始邮件
                       
                     

发件人："USTC-xlab"< ***@***.*** &gt;;

发件时间：2023/7/19 12:03

收件人："USTC-xlab/MOSR"< ***@***.*** &gt;;

抄送人："dadazhetang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [USTC-xlab/MOSR] 运行test后有报错_pickle.UnpicklingError: pickle data was truncated (Issue #1)




 
This appears to be due to file corruption and you can re-generate a low resolution MSI image. Also note that our input folder is specified in the yml file and does not require the pickle library to import.

**Comment by USTC-xlab** [comment]
Maybe that's the problem. We have released the "pretrained_models" that named as `MOSR.2.0.pth`, and its filesize is 290 MB. You can find and download it at our Github homepage.

**Comment by dadazhetang** [comment]
Thank you very much for your patient responses. However, I couldn't find the MOSR.2.0.pth file on your homepage. If possible, could you please let me know where to find it? I am deeply grateful for your help because I'm relatively new to GitHub and may have difficulty locating what I'm looking for.Once again, I sincerely thank you for dedicating so much of your time to answering my questions

**Comment by dadazhetang** [comment]
OH,I have got it,thank you so much again for your patient responses
